# GET https://www.google.com

# POST http://localhost:5000/shorten
# Content-Type: application/json

# {
#   "longurl": "https://www.apple.com/shop/product/MLYU3AM/A/140w-usb-c-power-adapter?fnode=e6480a33d043ce8009a7c37b44a75101a8cdaca498df0af9dcee9f79e50cc9b99e739b1f18ee7867d66caa957ff8687f59fb7c83fb574f45aba9f95199e8cc8200e32867476af17d522732659173c9bf86c326c9e7aa3e9cc158eeed8bb8d1d4"
# }

# POST http://localhost:5000/shorten
# Content-Type: application/json

# {
#   "longurl": "https://www.npmjs.com/package/is-valid-http-url"
# }

POST http://localhost:5000/shorten
Content-Type: application/json

{
  "longurl": "https://www.straitstimes.com/singapore/politics/experience-networks-from-covid-19-essential-in-tackling-future-challenges-vivian-balakrishnan"
}

# GET http://localhost:5000/gAB14Vz-N
